// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyB32ETTVCuBencskmh-wpwg-zSvKEqISEQ",
    authDomain: "aks-samy-farm.firebaseapp.com",
    projectId: "aks-samy-farm",
    storageBucket: "aks-samy-farm.firebasestorage.app",
    messagingSenderId: "352007251404",
    appId: "1:352007251404:web:838014ee7cac31e5922969",
    measurementId: "G-XE7YDKQFHN",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyrTmO4EDxfhAL73hqxjDCJXO4JRMUKKk',
    appId: '1:352007251404:android:fff2574404b88be4922969',
    messagingSenderId: '352007251404',
    projectId: 'aks-samy-farm',
    storageBucket: 'aks-samy-farm.firebasestorage.app',
  );
}
